### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by TomMaullin**
It addresses all formatting and code layout issues, i.e. issues #3 and #15 .

### CODE REVIEW

**Comment by TomMaullin** [comment]
Hi @cmaumet 

All tests now pass and this branch is review ready!

Cheers,
Tom M

**Comment by cmaumet** [comment]
As discussed on our call yesterday, I am happy for you to merge this refactoring (once conflicts are resolved).

**Comment by cmaumet** [comment]
@TomMaullin: before merging, can you deal with the recommendations send by the bot "pep8speaks" in the comment above? Thanks!

**Comment by TomMaullin** [comment]
@cmaumet Yes, sure! Do you know how to make the bot update it's comment?

**Comment by cmaumet** [comment]
I think there is no need to retrigger pep8speaks. It should automatically update the initial comment as you make changes (cf. https://github.com/OrkoHunter/pep8speaks).

**Comment by cmaumet** [comment]
@TomMaullin: have you installed a PEP8 linter in your code editor? This will help fixing those issues directly on your machine rather than having to push changes to check the bot message each time. 

For sublime-text (if that's the editor you are using), see https://github.com/SublimeLinter/SublimeLinter-pycodestyle (https://github.com/incf-nidash/nidmresults-fslhtml/issues/3). If you are using another text editor, you will probably find another linter online. Let me know if you need some help to get this installed.

**Comment by TomMaullin** [comment]
@cmaumet I've had some issues trying to get this to work in my sublime text editor. For some reason whenever I install this or try to proof read any file using it sublime becomes non-responsive and eventually has to be shut down.

**Comment by TomMaullin** [comment]
Hi @cmaumet ,

This PR should now be PEP8 compliant! Are you happy for me to merge?

**Comment by cmaumet** [comment]
Congrats! Yes, sure!

**Pull request merged**
