### PR TITLE
Cluster P values

### PR DESCRIPTION
**Pull request by TomMaullin**
~~This PR is a fork of PR #23. Therefore PR #23 must be merged before this PR can be.~~

This PR adds cluster P values to the cluster table display (a feature that was already included in a previous PR but has somehow escaped merge). It also includes hard coded tests for the cluster table based on the original output of FEAT for some of the input data.

### CODE REVIEW

**Comment by TomMaullin** [comment]
Hi @cmaumet ,

I have now added the requested tests of the cluster and peaks tables. For the group level analyses I have added tests which were created using the original FEAT reports data (which can be checked against [here](
https://gist.github.com/TomMaullin/f5aa946ee8077a7d8ab20235242ae261) and [here](https://gist.github.com/TomMaullin/b522e06b67f74a0493ca2b2f7b416984)). For the subject level analyses I have added one test for `fsl_default` (using a combination of the [FEAT](https://gist.github.com/TomMaullin/276fee6e3eacd52a540741b1f5b40acd) report and [nidm ttl](https://gist.github.com/TomMaullin/7060bd490120119477fdd57427a18a6b)) and one test for `ex_spm_default` (using previously generated displays and verifying using the nidm ttl).

This PR should now be ready for review!

**Comment by cmaumet** [comment]
@TomMaullin: thanks for this! Is it okay to first focus on #23 first and then I'll review this PR once it's rebased?

**Comment by TomMaullin** [comment]
Hi @cmaumet ,

This PR has now been rebased to the master and is ready for review! The changes in this PR are quite small so probably do not require much time spent on them. I have realized though that one test was unstable and had to change it as there were two peaks in a cluster which both had the same value which happened to be the maxima of the cluster. As a result the cluster table interchangably reported either peak as the maxima of the cluster.

**Comment by cmaumet** [comment]
+1 to merge!

**Comment by cmaumet** [comment]
Thanks @TomMaullin this looks good to me! I am happy for you to merge.

**Pull request merged**
