### PR TITLE
Contrast Vector

### PR DESCRIPTION
**Pull request by TomMaullin**
This PR adds an image of the contrast vector, the contrast vectors name and the values of the contrast vector to the displays for SPM data in order to address issue #18 . This is forked from the cleanUP branch and needs PR #16 to be merged before merging.

### CODE REVIEW

**Comment by TomMaullin** [comment]
Hi @cmaumet , This branch is also now ready for review!

**Comment by TomMaullin** [comment]
Hi @cmaumet ,

This PR is now ready for review! For some reason the PEP8 bot has stopped updating on this PR which is strange... but I've created an identical PR on my repository and the PEP8 bot still is updating on that one and says that this branch has no errors (see https://github.com/tommaullin/nidmresults-fslhtml/pull/1 ).

Please let me know if you have any comments/further feedback!

**Comment by cmaumet** [comment]
Hi @TomMaullin,

Can you try to delete the comment sent out by pep8speaks and then send another commit to retrigger it? Maybe this will solve the problem.

**Comment by TomMaullin** [comment]
Hi @cmaumet ,

I have now done this but the PEP8 bot doesn't seem to be coming back! I'm not sure why this is!

**Comment by cmaumet** [comment]
Hi @TomMaullin,

I really like the images of the contrast vectors! They are very nice!

In some of the examples, it looks like 1 --> black and 0 ---> white, e.g. `ex_spm_temporal_derivative_test`

screen shot 2018-02-14 at 14 31 08

while in others 1 --> white `ex_spm_group_ols_test`
screen shot 2018-02-14 at 14 32 40

For consistency with the grey levels in the design matrix, do you think we could always have 1 --> white and 0 --> black?

**Comment by cmaumet** [comment]
@TomMaullin: do you think you could rebase this branch on `master`? Currently the "file changes" pane includes a lot of updates we have merged already which makes it difficult to review. Please do a backup copy before rebasing just in case :) And let me know if you need help to find the actual commands.

**Comment by TomMaullin** [comment]
Hi @cmaumet , Yes sure! What you have found in 'ex_spm_group_ols_test' looks as though it could be a slight error as it appears the border for the contrast vector is missing. I shall investigate this further and let you know when the colours have been changed in the way you have specified and the code has been rebased!

**Comment by TomMaullin** [comment]
Hi Camille,

I have now resolved the inverted colors issues and rebased as requested! I think I've managed to trip up the PEP8 bot again however as on my version of this PR it tells me there is nothing left to resolve!

Please let me know if you have any further feedback - otherwise I think this is ready!

**Comment by cmaumet** [comment]
Looks good to me! Thanks! Let's merge.

**Pull request merged**
